"""
Django settings for shoppage project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES_DIR = os.path.join(BASE_DIR,'templates')
STATIC_DIR = os.path.join(BASE_DIR,'static')
MEDIA_DIR = os.path.join(BASE_DIR,'media')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8q0ru!x=&mz#^w3am9&r5gwt*d+&yqv9u=y@xu+h=y^*pnc6ak'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['khoaphamdev.pythonanywhere.com','localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'basic_app',
    # 'clear_cache',
    'django.contrib.humanize',
    # 'bootstrap',
    # 'fontawesome',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shoppage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shoppage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
            'default': {
                        'ENGINE': 'django.db.backends.mysql',
                        'OPTIONS': {
                                    'read_default_file': '/path/to/my.cnf',
                                    },
                        'NAME': 'khoaphamdev$shoppage',
                        'USER': 'khoaphamdev',
                        'PASSWORD': 'shop_page',
                        'HOST': 'khoaphamdev.mysql.pythonanywhere-services.com',   # Or an IP Address that your DB is hosted on
                        }
            }

# ???
#
# DATABASES = {
#             'default': {
#                         'ENGINE': 'django.db.backends.mysql',
#                         'OPTIONS': {
#                                     'read_default_file': '/path/to/my.cnf',
#                                     },
#                         #   'NAME': 'shop_page_update_customer',
#                         'NAME': 'shop_page',
#                         'USER': 'root',
#                         'PASSWORD': '',
#                         'HOST': '',   # Or an IP Address that your DB is hosted on
#                         'PORT': '3306',
#                         }
#             }











# [client]
# database = NAME
# user = USER
# password = PASSWORD
# default-character-set = utf8_general_ci

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [STATIC_DIR,]
STATICFILES_DIRS =[STATIC_DIR,]

STATIC_ROOT  = '/home/khoaphamdev/django_shop_page/shoppage/static'
#media
MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'bluenight0105@gmail.com'
EMAIL_HOST_PASSWORD = 'latelyyou'
EMAIL_USE_TLS = True
ACCOUNT_EMAIL_VERIFICATION = 'none'


# DEFAULT_FROM_EMAIL ='bluenight0105@gmail.com'

    # CUSTOM FILE settings.py
# try:
#     from  shoppage.local_settings import *
# except ImportError:
#     pass
